name: Bug
description: File a bug report
title: "[BUG]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you do? What happened? What did you expect to happen?
      placeholder: Put your description of the bug here.
    validations:
      required: true
  - type: textarea
    id: versions
    attributes:
      label: Versions
      description: Specify the agent version 
      placeholder: Azure DevOps version 2.100.1
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Please copy and paste any relevant log output. You can find it in the _diag folder or on the pipelines logs on ADO side
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true